version = 0.1

[default.deploy.parameters]
stack_name = "jewelry-frontend"
resolve_s3 = true
s3_prefix = "jewelry-frontend"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=prod"
confirm_changeset = true

[dev.deploy.parameters]
stack_name = "jewelry-frontend-dev"
resolve_s3 = true
s3_prefix = "jewelry-frontend-dev"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=dev"
confirm_changeset = false

[staging.deploy.parameters]
stack_name = "jewelry-frontend-staging"
resolve_s3 = true
s3_prefix = "jewelry-frontend-staging"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=staging"
confirm_changeset = false

[prod.deploy.parameters]
stack_name = "jewelry-frontend-prod"
resolve_s3 = true
s3_prefix = "jewelry-frontend-prod"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=prod"
confirm_changeset = false
